apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-dynamo-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::957950410212:role/AmazonEKSLoadBalancerControllerRole
